# Generated by Django 4.2.8 on 2026-08-17 11:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timeline_start', models.DateField(blank=True, null=True)),
                ('timeline_end', models.DateField(blank=True, null=True)),
                ('units_total', models.IntegerField(default=0)),
                ('units_sold', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('construction', 'Under Construction'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('structural_specs', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('size', models.IntegerField(help_text='Size in square feet')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField(default=1)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('land', 'Land'), ('mixed-use', 'Mixed-Use')], default='apartment', max_length=20)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, help_text='Comma-separated features')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('construction', 'Under Construction')], default='available', max_length=20)),
                ('images', models.JSONField(default=list, help_text='List of image URLs')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.project')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
